
### Создание новой книги
POST http://localhost:8080/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlRFU1QzQGdtYWlsLmNvbSIsImV4cCI6MTcxNzc2ODA0NCwidXNlcklkIjo0fQ.3Ingks_fc88HJnK1ndXhD4ZMp5omJMFRoWWFE01l4DI


{
  "Title": "TEST4",
  "Description": "TEST4",
  "Citation": "TEST4"
}
