
### Обновление конкретной книги
PUT http://localhost:8080/books/2
Content-Type: application/json

{
  "Title": "Историия древней греции",
  "Description": "Краткое ввдение,1 курс",
  "Citation": "Греки считали рабов и женщин умственно не полнаценными"
}
